# Created by: Gabriel Simeoni
# Github: https://github.com/xiaoruqinzhe || Linkedin: https://linkedin.com/in/gabrielsimeoni
# Up and configure postgres
version: '3.1'

services:

  db:
    image: postgres
    mem_limit: 1024MB
    mem_reservation: 1G
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: sqlnode
    ports:
      - "5432:5432"